/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CancelMsiResponse {
    
    public String contentType;

    public CancelMsiResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.Error error;

    public CancelMsiResponse withError(au.gov.amsa.egc.egc_client.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    
    public Integer statusCode;

    public CancelMsiResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CancelMsiResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public String cancelMsi400TextWildcardString;

    public CancelMsiResponse withCancelMsi400TextWildcardString(String cancelMsi400TextWildcardString) {
        this.cancelMsi400TextWildcardString = cancelMsi400TextWildcardString;
        return this;
    }
    
    /**
     * Unauthorized (must authenticate)
     */
    
    public String cancelMsi401TextWildcardString;

    public CancelMsiResponse withCancelMsi401TextWildcardString(String cancelMsi401TextWildcardString) {
        this.cancelMsi401TextWildcardString = cancelMsi401TextWildcardString;
        return this;
    }
    
    /**
     * Not allowed
     */
    
    public String cancelMsi403TextWildcardString;

    public CancelMsiResponse withCancelMsi403TextWildcardString(String cancelMsi403TextWildcardString) {
        this.cancelMsi403TextWildcardString = cancelMsi403TextWildcardString;
        return this;
    }
    
    /**
     * Resource Not Found
     */
    
    public String cancelMsi404TextWildcardString;

    public CancelMsiResponse withCancelMsi404TextWildcardString(String cancelMsi404TextWildcardString) {
        this.cancelMsi404TextWildcardString = cancelMsi404TextWildcardString;
        return this;
    }
    
    /**
     * Unexpected error on the server
     */
    
    public String cancelMsi500TextWildcardString;

    public CancelMsiResponse withCancelMsi500TextWildcardString(String cancelMsi500TextWildcardString) {
        this.cancelMsi500TextWildcardString = cancelMsi500TextWildcardString;
        return this;
    }
    
    public CancelMsiResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
