/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.operations;

import au.gov.amsa.egc.egc_client.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CancelMsiRequest {
    /**
     * unique msi identifier
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public CancelMsiRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public CancelMsiRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
