/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateMsiResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public CreateMsiResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.Error error;

    public CreateMsiResponse withError(au.gov.amsa.egc.egc_client.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * The unique identifier of the newly created MSI
     */
    
    public String msiId;

    public CreateMsiResponse withMsiId(String msiId) {
        this.msiId = msiId;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public CreateMsiResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public CreateMsiResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public String createMsi400TextWildcardString;

    public CreateMsiResponse withCreateMsi400TextWildcardString(String createMsi400TextWildcardString) {
        this.createMsi400TextWildcardString = createMsi400TextWildcardString;
        return this;
    }
    
    /**
     * Unauthorized (must authenticate)
     */
    
    public String createMsi401TextWildcardString;

    public CreateMsiResponse withCreateMsi401TextWildcardString(String createMsi401TextWildcardString) {
        this.createMsi401TextWildcardString = createMsi401TextWildcardString;
        return this;
    }
    
    /**
     * Not allowed
     */
    
    public String createMsi403TextWildcardString;

    public CreateMsiResponse withCreateMsi403TextWildcardString(String createMsi403TextWildcardString) {
        this.createMsi403TextWildcardString = createMsi403TextWildcardString;
        return this;
    }
    
    /**
     * Unexpected error on the server
     */
    
    public String createMsi500TextWildcardString;

    public CreateMsiResponse withCreateMsi500TextWildcardString(String createMsi500TextWildcardString) {
        this.createMsi500TextWildcardString = createMsi500TextWildcardString;
        return this;
    }
    
    public CreateMsiResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
