/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetMsiStatusResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetMsiStatusResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.Error error;

    public GetMsiStatusResponse withError(au.gov.amsa.egc.egc_client.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetMsiStatusResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetMsiStatusResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.StatusExtended statusExtended;

    public GetMsiStatusResponse withStatusExtended(au.gov.amsa.egc.egc_client.models.shared.StatusExtended statusExtended) {
        this.statusExtended = statusExtended;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public String getMsiStatus400TextWildcardString;

    public GetMsiStatusResponse withGetMsiStatus400TextWildcardString(String getMsiStatus400TextWildcardString) {
        this.getMsiStatus400TextWildcardString = getMsiStatus400TextWildcardString;
        return this;
    }
    
    /**
     * Unauthorized (must authenticate)
     */
    
    public String getMsiStatus401TextWildcardString;

    public GetMsiStatusResponse withGetMsiStatus401TextWildcardString(String getMsiStatus401TextWildcardString) {
        this.getMsiStatus401TextWildcardString = getMsiStatus401TextWildcardString;
        return this;
    }
    
    /**
     * Not allowed
     */
    
    public String getMsiStatus403TextWildcardString;

    public GetMsiStatusResponse withGetMsiStatus403TextWildcardString(String getMsiStatus403TextWildcardString) {
        this.getMsiStatus403TextWildcardString = getMsiStatus403TextWildcardString;
        return this;
    }
    
    /**
     * Resource Not Found
     */
    
    public String getMsiStatus404TextWildcardString;

    public GetMsiStatusResponse withGetMsiStatus404TextWildcardString(String getMsiStatus404TextWildcardString) {
        this.getMsiStatus404TextWildcardString = getMsiStatus404TextWildcardString;
        return this;
    }
    
    /**
     * Unexpected error on the server
     */
    
    public String getMsiStatus500TextWildcardString;

    public GetMsiStatusResponse withGetMsiStatus500TextWildcardString(String getMsiStatus500TextWildcardString) {
        this.getMsiStatus500TextWildcardString = getMsiStatus500TextWildcardString;
        return this;
    }
    
    public GetMsiStatusResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
