/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetMsisResponse {
    
    public String contentType;

    public GetMsisResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.Error error;

    public GetMsisResponse withError(au.gov.amsa.egc.egc_client.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMsisResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMsisResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetMsis200ApplicationJSON getMsis200ApplicationJSONObject;

    public GetMsisResponse withGetMsis200ApplicationJSONObject(GetMsis200ApplicationJSON getMsis200ApplicationJSONObject) {
        this.getMsis200ApplicationJSONObject = getMsis200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public String getMsis400TextWildcardString;

    public GetMsisResponse withGetMsis400TextWildcardString(String getMsis400TextWildcardString) {
        this.getMsis400TextWildcardString = getMsis400TextWildcardString;
        return this;
    }
    
    /**
     * Unauthorized (must authenticate)
     */
    
    public String getMsis401TextWildcardString;

    public GetMsisResponse withGetMsis401TextWildcardString(String getMsis401TextWildcardString) {
        this.getMsis401TextWildcardString = getMsis401TextWildcardString;
        return this;
    }
    
    /**
     * Not allowed
     */
    
    public String getMsis403TextWildcardString;

    public GetMsisResponse withGetMsis403TextWildcardString(String getMsis403TextWildcardString) {
        this.getMsis403TextWildcardString = getMsis403TextWildcardString;
        return this;
    }
    
    /**
     * Unexpected error on the server
     */
    
    public String getMsis500TextWildcardString;

    public GetMsisResponse withGetMsis500TextWildcardString(String getMsis500TextWildcardString) {
        this.getMsis500TextWildcardString = getMsis500TextWildcardString;
        return this;
    }
    
    public GetMsisResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
