/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetTokenResponse {
    /**
     * Bad request
     */
    
    public String fourHundredTextWildcardRes;

    public GetTokenResponse withFourHundredTextWildcardRes(String fourHundredTextWildcardRes) {
        this.fourHundredTextWildcardRes = fourHundredTextWildcardRes;
        return this;
    }
    
    /**
     * Unauthorized (must authenticate)
     */
    
    public String fourHundredAndOneTextWildcardRes;

    public GetTokenResponse withFourHundredAndOneTextWildcardRes(String fourHundredAndOneTextWildcardRes) {
        this.fourHundredAndOneTextWildcardRes = fourHundredAndOneTextWildcardRes;
        return this;
    }
    
    /**
     * Unexpected error on the server
     */
    
    public String fiveHundredTextWildcardRes;

    public GetTokenResponse withFiveHundredTextWildcardRes(String fiveHundredTextWildcardRes) {
        this.fiveHundredTextWildcardRes = fiveHundredTextWildcardRes;
        return this;
    }
    
    /**
     * token and expiry time
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.AuthenticationResponse authenticationResponse;

    public GetTokenResponse withAuthenticationResponse(au.gov.amsa.egc.egc_client.models.shared.AuthenticationResponse authenticationResponse) {
        this.authenticationResponse = authenticationResponse;
        return this;
    }
    
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetTokenResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.Error error;

    public GetTokenResponse withError(au.gov.amsa.egc.egc_client.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetTokenResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetTokenResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetTokenResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
