/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetTokenResponse {
    /**
     * token and expiry time
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.AuthenticationResponse authenticationResponse;

    public GetTokenResponse withAuthenticationResponse(au.gov.amsa.egc.egc_client.models.shared.AuthenticationResponse authenticationResponse) {
        this.authenticationResponse = authenticationResponse;
        return this;
    }
    
    
    public String contentType;

    public GetTokenResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public au.gov.amsa.egc.egc_client.models.shared.Error error;

    public GetTokenResponse withError(au.gov.amsa.egc.egc_client.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    
    public Integer statusCode;

    public GetTokenResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetTokenResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Bad request
     */
    
    public String getToken400TextWildcardString;

    public GetTokenResponse withGetToken400TextWildcardString(String getToken400TextWildcardString) {
        this.getToken400TextWildcardString = getToken400TextWildcardString;
        return this;
    }
    
    /**
     * Unauthorized (must authenticate)
     */
    
    public String getToken401TextWildcardString;

    public GetTokenResponse withGetToken401TextWildcardString(String getToken401TextWildcardString) {
        this.getToken401TextWildcardString = getToken401TextWildcardString;
        return this;
    }
    
    /**
     * Unexpected error on the server
     */
    
    public String getToken500TextWildcardString;

    public GetTokenResponse withGetToken500TextWildcardString(String getToken500TextWildcardString) {
        this.getToken500TextWildcardString = getToken500TextWildcardString;
        return this;
    }
    
    public GetTokenResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
