/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client;

import au.gov.amsa.egc.egc_client.utils.HTTPClient;
import au.gov.amsa.egc.egc_client.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0-alpha";
	public String sdkVersion = "0.5.1";
	public String genVersion = "2.143.2";
	public String userAgent = "speakeasy-sdk/java 0.5.1 2.143.2 1.0-alpha <no value>";
	
	
}