/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client;

import au.gov.amsa.egc.egc_client.utils.HTTPClient;
import au.gov.amsa.egc.egc_client.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0-alpha";
	public String sdkVersion = "0.14.0";
	public String genVersion = "2.258.0";
	public String userAgent = "speakeasy-sdk/java 0.14.0 2.258.0 1.0-alpha au.gov.amsa.egc.egc_client";
	
	
}