/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import au.gov.amsa.egc.egc_client.utils.DateTimeDeserializer;
import au.gov.amsa.egc.egc_client.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;


public class AuthenticationResponse {
    /**
     * An expiryTime should always accompany the token
     * because a requested validity duration may be 
     * capped by the server and the client needs to know 
     * what the resultant expiry time was.
     * 
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("expiryTime")
    public OffsetDateTime expiryTime;

    public AuthenticationResponse withExpiryTime(OffsetDateTime expiryTime) {
        this.expiryTime = expiryTime;
        return this;
    }
    
    @JsonProperty("token")
    public String token;

    public AuthenticationResponse withToken(String token) {
        this.token = token;
        return this;
    }
    
    public AuthenticationResponse(@JsonProperty("expiryTime") OffsetDateTime expiryTime, @JsonProperty("token") String token) {
        this.expiryTime = expiryTime;
        this.token = token;
  }
}
