/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BroadcastType {
    SAR_BROADCAST("SARBroadcast"),
    MET_BROADCAST("MetBroadcast"),
    NAV_BROADCAST("NavBroadcast"),
    PIRACY_BROADCAST("PiracyBroadcast");

    @JsonValue
    public final String value;

    private BroadcastType(String value) {
        this.value = value;
    }
}
