/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class Circle {
    @JsonProperty("lat")
    public Float lat;

    public Circle withLat(Float lat) {
        this.lat = lat;
        return this;
    }
    
    @JsonProperty("lon")
    public Float lon;

    public Circle withLon(Float lon) {
        this.lon = lon;
        return this;
    }
    
    @JsonProperty("radiusNm")
    public Float radiusNm;

    public Circle withRadiusNm(Float radiusNm) {
        this.radiusNm = radiusNm;
        return this;
    }
    
    public Circle(@JsonProperty("lat") Float lat, @JsonProperty("lon") Float lon, @JsonProperty("radiusNm") Float radiusNm) {
        this.lat = lat;
        this.lon = lon;
        this.radiusNm = radiusNm;
  }
}
