/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Error - an error message (response)
 */

public class Error {
    /**
     * an error message (response)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cause")
    public Error cause;

    public Error withCause(Error cause) {
        this.cause = cause;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errorMessage")
    public String errorMessage;

    public Error withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errorType")
    public String errorType;

    public Error withErrorType(String errorType) {
        this.errorType = errorType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stackTrace")
    public String stackTrace;

    public Error withStackTrace(String stackTrace) {
        this.stackTrace = stackTrace;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("statusCode")
    public Integer statusCode;

    public Error withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    public Error(){}
}
