/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class MetArea {
    @JsonProperty("metAreaCode")
    public Integer metAreaCode;

    public MetArea withMetAreaCode(Integer metAreaCode) {
        this.metAreaCode = metAreaCode;
        return this;
    }
    
    public MetArea(@JsonProperty("metAreaCode") Integer metAreaCode) {
        this.metAreaCode = metAreaCode;
  }
}
