/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MetBroadcast - the details of the broadcast particular to the broadcast type
 */

public class MetBroadcast {
    @JsonProperty("area")
    public Object area;

    public MetBroadcast withArea(Object area) {
        this.area = area;
        return this;
    }
    
    @JsonProperty("priority")
    public NonSARPriority priority;

    public MetBroadcast withPriority(NonSARPriority priority) {
        this.priority = priority;
        return this;
    }
    
    public MetBroadcast(@JsonProperty("area") Object area, @JsonProperty("priority") NonSARPriority priority) {
        this.area = area;
        this.priority = priority;
  }
}
