/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NavBroadcast - the details of the broadcast particular to the broadcast type
 */

public class NavBroadcast {
    @JsonProperty("navBroadcastArea")
    public Object navBroadcastArea;

    public NavBroadcast withNavBroadcastArea(Object navBroadcastArea) {
        this.navBroadcastArea = navBroadcastArea;
        return this;
    }
    
    @JsonProperty("priority")
    public NonSARPriority priority;

    public NavBroadcast withPriority(NonSARPriority priority) {
        this.priority = priority;
        return this;
    }
    
    public NavBroadcast(@JsonProperty("navBroadcastArea") Object navBroadcastArea, @JsonProperty("priority") NonSARPriority priority) {
        this.navBroadcastArea = navBroadcastArea;
        this.priority = priority;
  }
}
