/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class NavCoastalWarningArea {
    @JsonProperty("coastalWarningAreaCode")
    public String coastalWarningAreaCode;

    public NavCoastalWarningArea withCoastalWarningAreaCode(String coastalWarningAreaCode) {
        this.coastalWarningAreaCode = coastalWarningAreaCode;
        return this;
    }
    
    @JsonProperty("navAreaCode")
    public Integer navAreaCode;

    public NavCoastalWarningArea withNavAreaCode(Integer navAreaCode) {
        this.navAreaCode = navAreaCode;
        return this;
    }
    
    /**
     * Subject indicator associated with a Coastal Warning
     *             
     * 
     */
    @JsonProperty("subjectIndicator")
    public SubjectIndicator subjectIndicator;

    public NavCoastalWarningArea withSubjectIndicator(SubjectIndicator subjectIndicator) {
        this.subjectIndicator = subjectIndicator;
        return this;
    }
    
    public NavCoastalWarningArea(@JsonProperty("coastalWarningAreaCode") String coastalWarningAreaCode, @JsonProperty("navAreaCode") Integer navAreaCode, @JsonProperty("subjectIndicator") SubjectIndicator subjectIndicator) {
        this.coastalWarningAreaCode = coastalWarningAreaCode;
        this.navAreaCode = navAreaCode;
        this.subjectIndicator = subjectIndicator;
  }
}
