/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * NumRepetitions - the number of non-echo repeats of a broadcast (so total number of broadcasts not 
 * including echoes will be that number plus one being the initial broadcast)
 * 
 */
public enum NumRepetitions {
    ONCE("ONCE"),
    TWICE("TWICE"),
    TILL_CANCELLED("TILL_CANCELLED");

    @JsonValue
    public final String value;

    private NumRepetitions(String value) {
        this.value = value;
    }
}
