/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PiracyBroadcast - the details of the broadcast particular to the broadcast type
 */

public class PiracyBroadcast {
    @JsonProperty("piracyBroadcastArea")
    public Object piracyBroadcastArea;

    public PiracyBroadcast withPiracyBroadcastArea(Object piracyBroadcastArea) {
        this.piracyBroadcastArea = piracyBroadcastArea;
        return this;
    }
    
    @JsonProperty("priority")
    public NonSARPriority priority;

    public PiracyBroadcast withPriority(NonSARPriority priority) {
        this.priority = priority;
        return this;
    }
    
    public PiracyBroadcast(@JsonProperty("piracyBroadcastArea") Object piracyBroadcastArea, @JsonProperty("priority") NonSARPriority priority) {
        this.piracyBroadcastArea = piracyBroadcastArea;
        this.priority = priority;
  }
}
