/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class Rectangle {
    @JsonProperty("heightDegrees")
    public Float heightDegrees;

    public Rectangle withHeightDegrees(Float heightDegrees) {
        this.heightDegrees = heightDegrees;
        return this;
    }
    
    @JsonProperty("leftLon")
    public Float leftLon;

    public Rectangle withLeftLon(Float leftLon) {
        this.leftLon = leftLon;
        return this;
    }
    
    @JsonProperty("minLat")
    public Float minLat;

    public Rectangle withMinLat(Float minLat) {
        this.minLat = minLat;
        return this;
    }
    
    @JsonProperty("widthDegrees")
    public Float widthDegrees;

    public Rectangle withWidthDegrees(Float widthDegrees) {
        this.widthDegrees = widthDegrees;
        return this;
    }
    
    public Rectangle(@JsonProperty("heightDegrees") Float heightDegrees, @JsonProperty("leftLon") Float leftLon, @JsonProperty("minLat") Float minLat, @JsonProperty("widthDegrees") Float widthDegrees) {
        this.heightDegrees = heightDegrees;
        this.leftLon = leftLon;
        this.minLat = minLat;
        this.widthDegrees = widthDegrees;
  }
}
