/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class Repetition {
    /**
     * The time gap between broadcasts of the same MSI.   
     * The satellite service provider documentation should be 
     * consulted to determine what values are supported and 
     * under what criteria.      
     *     
     * 
     */
    @JsonProperty("intervalHours")
    public IntervalHours intervalHours;

    public Repetition withIntervalHours(IntervalHours intervalHours) {
        this.intervalHours = intervalHours;
        return this;
    }
    
    /**
     * the number of non-echo repeats of a broadcast (so total number of broadcasts not 
     * including echoes will be that number plus one being the initial broadcast)
     * 
     */
    @JsonProperty("number")
    public NumRepetitions number;

    public Repetition withNumber(NumRepetitions number) {
        this.number = number;
        return this;
    }
    
    public Repetition(@JsonProperty("intervalHours") IntervalHours intervalHours, @JsonProperty("number") NumRepetitions number) {
        this.intervalHours = intervalHours;
        this.number = number;
  }
}
