/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SARBroadcast - area is optional. If omitted then corresponds to the
 * entire coverage area.
 * 
 */

public class SARBroadcast {
    @JsonProperty("priority")
    public SARPriority priority;

    public SARBroadcast withPriority(SARPriority priority) {
        this.priority = priority;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sarArea")
    public Object sarArea;

    public SARBroadcast withSarArea(Object sarArea) {
        this.sarArea = sarArea;
        return this;
    }
    
    @JsonProperty("serviceType")
    public SARServiceType serviceType;

    public SARBroadcast withServiceType(SARServiceType serviceType) {
        this.serviceType = serviceType;
        return this;
    }
    
    public SARBroadcast(@JsonProperty("priority") SARPriority priority, @JsonProperty("serviceType") SARServiceType serviceType) {
        this.priority = priority;
        this.serviceType = serviceType;
  }
}
