/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SARPriority {
    SAFETY("SAFETY"),
    URGENCY("URGENCY"),
    DISTRESS("DISTRESS");

    @JsonValue
    public final String value;

    private SARPriority(String value) {
        this.value = value;
    }
}
