/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SARServiceType {
    SHORE_TO_SHIP_DISTRESS_ALERT("SHORE_TO_SHIP_DISTRESS_ALERT"),
    SAR_COORDINATION("SAR_COORDINATION"),
    SHORE_TO_SHIP_URGENCY_OR_SAFETY("SHORE_TO_SHIP_URGENCY_OR_SAFETY"),
    GENERAL("GENERAL");

    @JsonValue
    public final String value;

    private SARServiceType(String value) {
        this.value = value;
    }
}
