/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import au.gov.amsa.egc.egc_client.utils.SpeakeasyMetadata;


public class Security {
    @SpeakeasyMetadata("security:scheme=true,type=http,subtype=bearer,name=Authorization")
    public String bearer;

    public Security withBearer(String bearer) {
        this.bearer = bearer;
        return this;
    }
    
    public Security(){}
}
