/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package au.gov.amsa.egc.egc_client.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Status - ACTIVE means that the MSI has been taken off the submission queue
 * and marked as ready for broadcast (either immediately or at the next 
 * scheduled time depending on the type of broadcast). TODO discuss 
 * with satellite providers what this represents for them so that we can
 * end up with a common significance for clients.
 * 
 * These are the expected transitions between states (in PlantUML format):
 * 
 */
public enum Status {
    CREATED("CREATED"),
    SCHEDULED("SCHEDULED"),
    ACTIVE("ACTIVE"),
    FINISHED("FINISHED"),
    CANCELLING("CANCELLING"),
    CANCELLED("CANCELLED"),
    BROADCAST_ERROR("BROADCAST_ERROR"),
    CANCEL_ERROR("CANCEL_ERROR");

    @JsonValue
    public final String value;

    private Status(String value) {
        this.value = value;
    }
}
